### ISSUE TITLE
Incorrect preAuthAccessUri in object-store-service binding - hostname part is missing

### ISSUE THREAD

**Issue by doschkinow** [oracle/oci-service-broker#16]
after creating an object store bucket, the object-store-service binding returns following data in the corresponding secret: 

preAuthAccessUri: L3AvYnViR2s3UW10NmNtdHVjMDN1OWNGTzI1ZkhJLV90Ul93dHduR3BnQXh0QS9uL29yYXNlZW1lYWRlc2FuZGJveC9iL3Rlc3RidWNrZXQvby8=

which after base64 decoding gives: /p/bubGk7Qmt6cmtuc03u9cFO25fHI-_tR_wtwnGpgAxtA/n/oraseemeadesandbox/b/testbucket/o/

The expected prefix of, in my case, "https://objectstorage.ap-seoul-1.oraclecloud.com" is missing

I testefd this with oci-service-broker 1.3.1

**Comment by jayasheelankumar** [comment]
@doschkinow Thanks for pointing it out. Yes, the "preAuthAccessUri" provides only the URI without the regional endpoint. We do not hard code the OCI regional endpoints along with the preAuthAccessUri. We have updated the document with this information of what will the preAuthAccessUri field contain in [v1.3.2](https://github.com/oracle/oci-service-broker/blob/master/charts/oci-service-broker/docs/object-storage.md#response-credentials)

**Comment by ashokkkannan** [comment]
@doschkinow Please feel free to reopen the ticket if you still need any help with this.
