### ISSUE TITLE
Creation of stream instances does not work

### ISSUE THREAD

**Issue by doschkinow** [oracle/oci-service-broker#17]
The creation of streams instances does not work. The OSB outputs in its log:
java.net.UnknownHostException: streams.ap-seoul-1.streaming.oci.oraclecloud.com

Obviously, the Streams API Endpoint can't be resolved.

I tested this with OSB 1.3.0 and 1.3.1

**Comment by jayasheelankumar** [comment]
We have fixed this issue as apart of OSB 1.4.0. Closing this issue.
