### ISSUE TITLE
OSB does not support updating admin password for ATP

### ISSUE THREAD

**Issue by lake-of-dreams** [oracle/oci-service-broker#18]
We can update the password for atp in `ServiceInstance` parameters in k8s but that is not  propagated till OCI to actually update the password for the ATP database. We can update the admin password from OCI console - and same should be supported when ATP instance is created using OSB - or please let know if there is any specific reason that this feature has been left out.

1. I can see in https://github.com/oracle/oci-service-broker/blob/f5bd5ce0408fc4f59dbb573b8cd8406063025650/oci-service-broker/src/main/java/com/oracle/oci/osb/adapters/adb/AutonomousDatabaseAdapter.java#L299 that we do not read password from the update request - even when we can update the password on corresponding ServiceInstance itself

2. I can also see that in AutonomousDatabaseOCIClient.update - we check for existing values on the AutonomousDatabase instance and it does not expose getPassword and therefore there is not a way to check if password supplied is changed or not. But the UpdateAutonomousDatabaseDetails.Builder does support adding a new admin password and therefore I would assume it should be supported?

**Comment by jayasheelankumar** [comment]
We are supporting updating of Admin password in ATP and ADW as part of OSB 1.4.0. We are not supporting displaying of Admin password as part of Get as that would be a security risk. Closing this ticket.
