### ISSUE TITLE
Can not download oci-service-broker-1.3.2.tgz

### ISSUE THREAD

**Issue by mgueury** [oracle/oci-service-broker#20]
In the readme, there is this step:

curl https://github.com/oracle/oci-service-broker/releases/download/v1.3.2/oci-service-broker-1.3.2.tgz | tar xz

It should be 

curl -L https://github.com/oracle/oci-service-broker/releases/download/v1.3.2/oci-service-broker-1.3.2.tgz | tar xz

**Comment by ashokkkannan** [comment]
Thanks @mgueury for pointing this out. This is fixed in [v1.3.3.](https://github.com/oracle/oci-service-broker/releases/tag/v1.3.3)
