### ISSUE TITLE
Namespace configuration is not clear

### ISSUE THREAD

**Issue by mgueury** [oracle/oci-service-broker#21]
In the step to install the service broker, there is : 

kubectl create -f oci-service-broker/samples/oci-service-broker.yaml

The file contains a 
  url: http://oci-service-broker.<NAMESPACE_OF_OCI_SERVICE_BROKER>:8080

It works for me only with
  url: http://oci-service-broker:8080

It took me a huge time to get it working. I think:
- or the file oci-service-broker.yaml should not contain <NAMESPACE_OF_OCI_SERVICE_BROKER>
- or there should be a explanation about using namespace with the service broker
- or probably both

**Comment by jayasheelankumar** [comment]
@mgueury The space holder <NAMESPACE_OF_OCI_SERVICE_BROKER> is mainly to help people understand that, we can register a service broker with catalog, even if it is installed in a different namespace other than `default`. 

Yes, your right it will work with url "http://oci-service-broker:8080" when in default namespace. It will also work with url "http://oci-service-broker.default:8080"

**Comment by mgueury** [comment]
I do not mind how you prefer to formulate. You should change the doc to make this clearer.

**Comment by jayasheelankumar** [comment]
We have updated the document with necessary details. Thanks. Closing this issue for now.
