### ISSUE TITLE
OSS Stream service instance/binding should support Stream Pool OCID

### ISSUE THREAD

**Issue by mvandervliet** [oracle/oci-service-broker#23]
Depending on connection details, there are situations (such as kafka compatibility) where the provisioned Stream `serviceinstance` requires a known stream pool identifier. Therefore, two possible requirements:

1. Support a streamPoolId parameter in `oss-service` plan for `kind: ServiceInstance`
1. Provide a streamPoolId property in the associative `ServiceBinding` for `oss-service` type service instances.

**Comment by ashokkkannan** [comment]
Thanks @mvandervliet ! We will  look into adding support for this.

**Comment by jayasheelankumar** [comment]
We have added support for StreampoolId in OSB 1.4.0 during stream creation. Closing this issue. Thanks!
