### ISSUE TITLE
OSB should use stream.getLifecycleState to filter Deleted stream 

### ISSUE THREAD

**Issue by shudshi** [oracle/oci-service-broker#32]
In src/main/java/com/oracle/oci/osb/adapters/oss/OSSServiceAdapter.java, line 99, where it is handling conflict, there should be one more filter condition "!item. getLifecycleState().equals(Stream.LifecycleState.Deleted)" to filter delete OSS streams.

**Comment by shudshi** [comment]
https://github.com/oracle/oci-service-broker/blob/a8da5f7d211fa98665cf298b7c3d9638be59138b/oci-service-broker/src/main/java/com/oracle/oci/osb/adapters/oss/OSSServiceAdapter.java#L99

**Comment by shudshi** [comment]
Current OSB is complain this error message while an OSS stream with the same name is recreated after delete:
$ kubectl describe serviceinstance
...  
Warning  ProvisionCallFailed  4m44s (x8 over 6m52s)  service-catalog-controller-manager  Error provisioning ServiceInstance of ClusterServiceClass (K8S: "f28894d0-cf40-4cff-a19a-a6893f88dd67" ExternalName: "oss-service") at ClusterServiceBroker "oci-service-broker": Status: 409; ErrorMessage: ServiceExists; Description: A Conflicting service with same ID or parameters already exists; ResponseError: <nil>

**Comment by ashokkkannan** [comment]
@shudshi Thank you for reporting the issue. The fix is now available as part of the latest release [v1.5.1](https://github.com/oracle/oci-service-broker/releases/tag/v1.5.1)

**Comment by shudshi** [comment]
Thanks for the fix.
