### ISSUE TITLE
Failed to download "charts/oci-service-broker/."

### ISSUE THREAD

**Issue by lsarecz** [oracle/oci-service-broker#5]
When I try to install Service Broker and in Quick Setup I execute the command:
`helm install --devel charts/oci-service-broker/.  --name oci-service-broker --set ociCredentials.secretName=ocicredentials --set storage.etcd.useEmbedded=true --set tls.enabled=false`
I get an error:
`Error: failed to download "charts/oci-service-broker/." (hint: running helm repo update may help)`
But helm repo update didn't help, I still get the same error.
What could be the reason?

**Comment by IamPrvn** [comment]
You might not have downloaded the chart at location `charts/` in your local filesystem. 
Download any of the chart releases from here https://github.com/oracle/oci-service-broker/releases  in your `charts` folder and then you may run the helm install command.

Note : you may install chart by various ways
[Chart is on local filesystem]
By path to a packaged chart: helm install ./oci-service-broker.tgz
By path to an unpacked chart directory: helm install ./oci-service-broker
[Chart is on remote host]
By absolute URL: helm install https://example.com/charts/oci-service-broker.tgz
By chart reference and repo url: helm install --repo https://example.com/charts/ oci-service-broker

**Comment by lsarecz** [comment]
Thanks, that was really the issue. I unzipped it to a different folder, so it didn't find it. It could be explained in the guide to make it obvious.

**Comment by ashokkkannan** [comment]
> Thanks, that was really the issue. I unzipped it to a different folder, so it didn't find it. It could be explained in the guide to make it obvious.

Thanks for the feedback. We will update the documents to make this more clear.
